config/routes.rb
Rails.application.routes.draw do
  get 'analytic/index'
  get 'static/analytic'
  get 'static/index'
  resources :queries
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord
end

app/controllers/analytic_controller.rb
class AnalyticController < ApplicationController
  def index
    @queries = Query.all.group_by(&:user_ip)
    # top queries should return search and the number of time it was searched
    # Query has a search column and a user_ip column
    @top_queries = Query.all.group(:search).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  # GET /articles or /articles.json
  def index
    if params[:query].present?
      # search for articles with titles or content that match the query
      @articles = Article.where("title LIKE ? OR content LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
      save_query(params[:query], request.remote_ip)
    else
      @articles = Article.all
    end

    if turbo_frame_request?
      render partial: "articles", locals: { articles: @articles }
    end
  end


  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end


  def save_query(search, user_ip)
    last_query = Query.where(user_ip: user_ip).last

    if last_query.nil?
      Query.create(search: search, user_ip: user_ip)
    else
      if search.start_with?(last_query.search)
        last_query.update(search: search)
      elsif last_query.search.include?(search)
        # do nothing
      else
        Query.create(search: search, user_ip: user_ip)
      end
    end
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: %i[ show edit update destroy ]

  # GET /queries or /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1 or /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  # POST /queries or /queries.json
  def create
    @query = Query.new(query_params)

    respond_to do |format|
      if @query.save
        format.html { redirect_to query_url(@query), notice: "Query was successfully created." }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1 or /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to query_url(@query), notice: "Query was successfully updated." }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1 or /queries/1.json
  def destroy
    @query.destroy!

    respond_to do |format|
      format.html { redirect_to queries_url, notice: "Query was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_query
      @query = Query.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def query_params
      params.require(:query).permit(:search, :user_ip)
    end
end

app/helpers/analytic_helper.rb
module AnalyticHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/analytic/index.html.erb
<div class="w-full flex flex-col items-center justify-between">
  <h1 class="font-bold text-4xl text-center mb-4">Search Analytics</h1>
  <div class="w-full flex justify-between items-center">
    <div class="w-full flex flex-col items-center justify-center">
      <h2 class="font-bold text-2xl mb-2 text-center">User Search</h2>
      <% @queries.each do |user, searches| %>
        <h3 class="font-medium mb-4 text-lg"><%= user %> search for </h3>
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <% searches.each do |query| %>
            <div class="card bordered shadow-lg">
              <div class="card-body p-3">
                <h2 class="card-title text-2xl">
                  <%= query.search %>
                </h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="w-full flex flex-col items-center justify-center">
      <h2 class="font-bold text-2xl mb-2">Top Searches</h2>
        <table class="table w-full">
          <thead>
            <tr>
              <th>Search</th>
              <th>Count</th>
            </tr>
          </thead>
      <% @top_queries.each do |search, count| %>
          <tbody>
            <tr>
              <td><%= search %></td>
              <td><%= count %></td>
            </tr>
          </tbody>
        <% end %>
        </table>
    </div>
  </div>
</div>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class="card  bg-base-100 shadow-xl">
    <div class="card-body items-center text-center">
      <h2 class="card-title text-2xl">
        <%= article.title %>
      </h2>

      <p>
        <%= article.content %>
      </p>

      <div class="card-actions mt-2">
        <div class="join">
          <%= link_to "Show", article_path(article), class: "btn btn-sm btn-ghost join-item hover:bg-primary" %>
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-ghost join-item hover:bg-secondary" %>
          <%= button_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-ghost join-item hover:bg-error" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <div class="min-w-full grid grid-cols-1 lg:grid-cols-4 gap-4">
    <% @articles.each do |article| %>
      <%= turbo_frame_tag dom_id(article) do %>
        <%= render article %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Articles" %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-4xl">Articles</h1>
    <div>
      <%= form_with(url: articles_path, method: :get, data: { controller: "search-form", turbo_frame: "articles", turbo_action: "advance" }) do |form| %>
        <div class="join">
          <%= form.label :query, class: "input input-bordered flex items-center gap-2" do  %>
            Search
            <%= form.text_field :query, class: "grow w-full max-w-xs", data: {
              action: "input->search-form#search"
            } %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= link_to "New article", new_article_path, class: "btn btn-outline btn-primary" %>
  </div>

  <div>
    <%= render "articles" %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <%= link_to "Edit this article", edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this article", @article, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="dark">
  <head>
    <title>Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.11.1/dist/full.min.css" rel="stylesheet" type="text/css" />

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/queries/_form.html.erb
<%= form_with(model: query, class: "contents") do |form| %>
  <% if query.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
        <% query.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :search %>
    <%= form.text_field :search, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :user_ip %>
    <%= form.text_field :user_ip, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/queries/_query.html.erb
<div id="<%= dom_id query %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Search:</strong>
    <%= query.search %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User ip:</strong>
    <%= query.user_ip %>
  </p>

</div>

app/views/queries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing query</h1>

  <%= render "form", query: @query %>

  <%= link_to "Show this query", @query, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to queries", queries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/queries/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Queries" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Queries</h1>
    <%= link_to "New query", new_query_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="queries" class="min-w-full">
    <% @queries.each do |query| %>
      <%= render query %>
      <p>
        <%= link_to "Show this query", query, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/queries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New query</h1>

  <%= render "form", query: @query %>

  <%= link_to "Back to queries", queries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/queries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @query %>

    <%= link_to "Edit this query", edit_query_path(@query), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to queries", queries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this query", @query, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="navbar bg-base-200 shadow-lg">
  <div class="navbar-start">
  </div>
  <div class="navbar-center">
    <%= link_to "Real Time Search", root_path, class: "btn btn-ghost text-2xl" %>
  </div>
  <div class="navbar-end">
    <%= link_to "Analytics", analytic_index_path, class: "btn btn-secondary text-xl" %>
  </div>
</header>